# Name of the domain bridge, used for node naming and logging
name: albabot2
from_domain: 62
to_domain: 112
topics:
  pinky_battery_present:
    type: std_msgs/msg/Float32
    remap: /albabot_2/pinky_battery_present

  tracked_pose:
    type: geometry_msgs/msg/PoseStamped
    remap: /albabot_2/tracked_pose
