# Name of the domain bridge, used for node naming and logging
name: albabot_1
from_domain: 74
to_domain: 112
topics:
  pinky_battery_present:
    type: std_msgs/msg/Float32
    remap: /albabot_1/pinky_battery_present

  tracked_pose:
    type: geometry_msgs/msg/PoseStamped
    remap: /albabot_1/tracked_pose
