# Name of the domain bridge, used for node naming and logging
name: albabot3_from
from_domain: 58
to_domain: 112
topics:
  pinky_battery_present:
    type: std_msgs/msg/Float32
    remap: /albabot3/pinky_battery_present

  tracked_pose:
    type: geometry_msgs/msg/PoseStamped
    remap: /albabot3/tracked_pose

  command:
    type: std_msgs/msg/String
