domain_bridge:
  ros__parameters:
    ros2_domains:
      - 65
      - 68
      - 69
    topics:
      - name: "/robot48/angles_real"
        type: "mycobot_interfaces/msg/MycobotAngles"
        from_domain: "69"
        to_domain: "65"
        wait_for_publisher: true

      - name: "/robot48/coords_real"
        type: "mycobot_interfaces/msg/MycobotCoords"
        from_domain: "69"
        to_domain: "65"
        wait_for_publisher: true

      - name: "/robot48/angles_targ"
        type: "mycobot_interfaces/msg/MycobotAngles"
        from_domain: "65"
        to_domain: "69"
        wait_for_publisher: true

      - name: "/robot48/coords_targ"
        type: "mycobot_interfaces/msg/MycobotCoords"
        from_domain: "65"
        to_domain: "69"
        wait_for_publisher: true

      - name: "/robotb4/angles_real"
        type: "mycobot_interfaces/msg/MycobotAngles"
        from_domain: "68"
        to_domain: "65"
        wait_for_publisher: true

      - name: "/robotb4/coords_real"
        type: "mycobot_interfaces/msg/MycobotCoords"
        from_domain: "68"
        to_domain: "65"
        wait_for_publisher: true

      - name: "/robotb4/angles_targ"
        type: "mycobot_interfaces/msg/MycobotAngles"
        from_domain: "65"
        to_domain: "68"
        wait_for_publisher: true

      - name: "/robotb4/coords_targ"
        type: "mycobot_interfaces/msg/MycobotCoords"
        from_domain: "65"
        to_domain: "68"
        wait_for_publisher: true
